import { useParams, Link } from "react-router-dom";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ArrowRight, Zap, Shield, Settings, AlertCircle } from "lucide-react";
import SEOHead from "@/components/SEO/SEOHead";
import StructuredData from "@/components/SEO/StructuredData";
import { generateBreadcrumbSchema, generateArticleSchema, generateFAQSchema } from "@/lib/seo";

const componentData: Record<string, {
  title: string;
  description: string;
  icon: any;
  content: string;
  features: string[];
  applications: string[];
  faqs: Array<{ question: string; answer: string }>;
}> = {
  "braking-resistor": {
    title: "VFD Braking Resistor - Function, Selection & Installation",
    description: "Complete guide to VFD braking resistors. Learn when you need one, how to size it correctly, and installation best practices.",
    icon: Zap,
    content: "A braking resistor is an external resistor connected to the VFD to dissipate excess energy during deceleration...",
    features: [
      "Dissipates regenerative energy during rapid deceleration",
      "Protects VFD from overvoltage conditions",
      "Enables faster stopping times",
      "Prevents DC bus voltage spikes"
    ],
    applications: [
      "High inertia loads (centrifuges, flywheels)",
      "Frequent start-stop operations",
      "Rapid deceleration requirements",
      "Elevators and hoists",
      "Cranes and material handling"
    ],
    faqs: [
      {
        question: "When do I need a braking resistor for VFD?",
        answer: "You need a braking resistor when: 1) Deceleration time is shorter than natural motor coast-down, 2) High inertia loads, 3) Frequent start-stop cycles, 4) Overvoltage trips occur during stopping."
      },
      {
        question: "How to size VFD braking resistor?",
        answer: "Braking resistor sizing depends on: motor power, load inertia, deceleration time, and duty cycle. Formula: P = (J × ω²) / (2 × t), where J=inertia, ω=speed, t=decel time. Consult VFD manual for specific sizing charts."
      }
    ]
  },
  "line-choke": {
    title: "VFD Line Choke (Input Reactor) - Benefits & Selection Guide",
    description: "Comprehensive guide to VFD line chokes. Understand AC line reactors, benefits, sizing, and when they're required.",
    icon: Shield,
    content: "A line choke (input reactor) is an inductor connected between the power supply and VFD input...",
    features: [
      "Reduces input current harmonics (THD)",
      "Protects against line voltage transients",
      "Improves power factor",
      "Extends VFD capacitor life",
      "Reduces electromagnetic interference (EMI)"
    ],
    applications: [
      "Poor power quality environments",
      "Long cable runs from transformer",
      "Multiple VFDs on same supply",
      "Sensitive equipment nearby",
      "Compliance with IEEE 519 standards"
    ],
    faqs: [
      {
        question: "What does line choke do in VFD?",
        answer: "Line choke reduces input current harmonics, protects from voltage spikes, improves power factor, and extends VFD component life. Typically provides 3-5% impedance."
      },
      {
        question: "AC line reactor vs DC choke?",
        answer: "AC line reactor (input choke): Installed before VFD rectifier, reduces harmonics. DC choke: Installed in DC bus, smooths DC current. Both improve performance but serve different purposes."
      }
    ]
  },
  "emc-filter": {
    title: "EMC Filter for VFD - EMI Suppression & Installation",
    description: "Essential guide to VFD EMC filters. Learn about electromagnetic interference, filter types, and compliance requirements.",
    icon: AlertCircle,
    content: "An EMC (Electromagnetic Compatibility) filter reduces electromagnetic interference generated by VFD switching...",
    features: [
      "Reduces conducted and radiated EMI",
      "Protects sensitive electronic equipment",
      "Ensures CE/FCC compliance",
      "Reduces motor bearing currents",
      "Minimizes cable radiation"
    ],
    applications: [
      "Medical facilities",
      "Clean rooms",
      "Laboratories with sensitive equipment",
      "Installations near communication equipment",
      "Export machines requiring CE marking"
    ],
    faqs: [
      {
        question: "Why EMC filter is required in VFD?",
        answer: "EMC filter is required to: 1) Meet electromagnetic compatibility standards (CE/FCC), 2) Prevent interference with nearby electronics, 3) Reduce motor bearing currents, 4) Comply with installation regulations."
      },
      {
        question: "Where to install EMC filter in VFD?",
        answer: "Install EMC filter as close to VFD as possible (within 30cm). Use shielded cables. Ground filter housing properly. Mount on metal panel for better EMI suppression."
      }
    ]
  }
};

const ComponentPage = () => {
  const { component } = useParams<{ component: string }>();
  const data = component ? componentData[component] : null;

  if (!data) {
    return (
      <>
        <Header />
        <div className="container mx-auto px-4 py-16 text-center">
          <h1 className="text-4xl font-bold mb-4">Component Not Found</h1>
          <Button asChild>
            <Link to="/vfd-parts">Browse All Components</Link>
          </Button>
        </div>
        <Footer />
      </>
    );
  }

  const Icon = data.icon;
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: window.location.origin },
    { name: "VFD Parts", url: `${window.location.origin}/vfd-parts` },
    { name: data.title, url: window.location.href },
  ]);

  const articleSchema = generateArticleSchema({
    title: data.title,
    description: data.description,
    publishedDate: new Date().toISOString(),
    author: "VFD India Experts",
  });

  const faqSchema = generateFAQSchema(data.faqs);

  return (
    <>
      <SEOHead
        title={data.title}
        description={data.description}
        canonical={`https://yourdomain.com/vfd-components/${component}`}
      />
      <StructuredData data={[breadcrumbSchema, articleSchema, faqSchema]} />
      
      <Header />
      
      <main className="min-h-screen bg-gradient-to-b from-background to-muted/20">
        <div className="bg-gradient-to-r from-primary/10 via-primary/5 to-background border-b">
          <div className="container mx-auto px-4 py-16">
            <div className="max-w-4xl mx-auto">
              <Badge className="mb-4" variant="secondary">
                <Icon className="mr-1 h-4 w-4" />
                VFD Component
              </Badge>
              <h1 className="text-4xl md:text-5xl font-bold mb-6">{data.title}</h1>
              <p className="text-xl text-muted-foreground">{data.description}</p>
            </div>
          </div>
        </div>

        <div className="container mx-auto px-4 py-12 max-w-4xl">
          {/* Content */}
          <Card className="p-8 mb-8">
            <h2 className="text-2xl font-bold mb-4">Overview</h2>
            <p className="text-muted-foreground leading-relaxed">{data.content}</p>
          </Card>

          {/* Features & Benefits */}
          <Card className="p-8 mb-8">
            <h2 className="text-2xl font-bold mb-6">Key Features & Benefits</h2>
            <ul className="space-y-3">
              {data.features.map((feature, idx) => (
                <li key={idx} className="flex items-start gap-3">
                  <Icon className="h-5 w-5 text-primary shrink-0 mt-1" />
                  <span>{feature}</span>
                </li>
              ))}
            </ul>
          </Card>

          {/* Applications */}
          <Card className="p-8 mb-8">
            <h2 className="text-2xl font-bold mb-6">Common Applications</h2>
            <div className="grid md:grid-cols-2 gap-3">
              {data.applications.map((app, idx) => (
                <div key={idx} className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg">
                  <Settings className="h-4 w-4 text-primary" />
                  <span>{app}</span>
                </div>
              ))}
            </div>
          </Card>

          {/* FAQs */}
          <Card className="p-8 mb-8">
            <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
            <Accordion type="single" collapsible className="w-full">
              {data.faqs.map((faq, idx) => (
                <AccordionItem key={idx} value={`faq-${idx}`}>
                  <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
                  <AccordionContent className="text-muted-foreground">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </Card>

          {/* CTA */}
          <Card className="p-8 text-center bg-gradient-to-r from-primary/10 to-secondary/10">
            <h2 className="text-2xl font-bold mb-4">Need Help Selecting Components?</h2>
            <p className="text-muted-foreground mb-6">
              Our experts can recommend the right accessories for your VFD installation.
            </p>
            <div className="flex gap-4 justify-center">
              <Button size="lg" asChild>
                <Link to="/contact">Get Expert Advice</Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/shop">Browse VFDs</Link>
              </Button>
            </div>
          </Card>
        </div>
      </main>
      
      <Footer />
    </>
  );
};

export default ComponentPage;